// Command 10-text draws MSDF text over a 3D scene.
//
// A multi-channel signed distance field stores, per colour channel, the
// distance to the glyph outline. The shader takes the median of the three,
// which reconstructs sharp corners that a single-channel field would round
// off. One 48px atlas therefore stays crisp from caption size to headline
// size, with no mipmaps and no per-size rasterization.
//
// The atlas here was generated by this repository's own tool, not by the C++
// msdf-atlas-gen:
//
//	go run github.com/derekmwright/glyphengine/cmd/msdfatlas \
//	    -font MyFont.ttf -out assets/fonts/inter
//
// which is also what `task font` runs. Text is drawn by handing the engine
// MSDF overlay objects each frame; the same path draws UI labels and
// world-space signage.
//
//	go run ./10-text              # windowed
//	go run ./10-text -frames 90   # render 90 frames, then exit
//
// Escape quits.
package main

import (
	"embed"
	"flag"
	"fmt"
	"log"
	"runtime"

	"github.com/go-gl/mathgl/mgl32"

	glyph "github.com/derekmwright/glyphengine"
	"github.com/derekmwright/glyphengine/input"
	"github.com/derekmwright/glyphengine/renderer"
)

//go:embed assets
var assetsFS embed.FS

func init() {
	// GLFW must be called from the thread that initialized it.
	runtime.LockOSThread()
}

type game struct {
	camera *glyph.Camera
	font   *renderer.Font
	text   *renderer.MSDFText
	cube   glyph.Entity
}

func (g *game) Init(e *glyph.Engine) error {
	r := e.Renderer()

	// The atlas is a PNG plus a JSON of glyph metrics, loaded from any fs.FS.
	font, err := renderer.LoadFont(r, assetsFS, "assets/fonts/goregular.json", "assets/fonts/goregular.png")
	if err != nil {
		return err
	}
	g.font = font

	text, err := renderer.NewMSDFText(r, font)
	if err != nil {
		return err
	}
	g.text = text

	// Something behind the text, so it is clearly compositing over a 3D scene
	// rather than being drawn on a blank page.
	ground, err := r.CreatePlane(40, 40)
	if err != nil {
		return err
	}
	groundEnt := e.Spawn()
	e.C.Transform.Set(groundEnt, &glyph.Transform{Scale: mgl32.Vec3{1, 1, 1}})
	e.C.MeshRef.Set(groundEnt, &glyph.MeshRef{Mesh: ground, Roughness: 0.95})
	e.C.Color.Set(groundEnt, &glyph.Color{R: 0.28, G: 0.33, B: 0.27})
	e.C.Static.Set(groundEnt, &glyph.Static{})

	cube, err := r.CreateCube(1.0)
	if err != nil {
		return err
	}
	g.cube = e.Spawn()
	e.C.Transform.Set(g.cube, &glyph.Transform{
		Position: mgl32.Vec3{0, 1.2, 0},
		Scale:    mgl32.Vec3{2, 2, 2},
	})
	e.C.MeshRef.Set(g.cube, &glyph.MeshRef{Mesh: cube, Metallic: 0.1, Roughness: 0.45})
	e.C.Color.Set(g.cube, &glyph.Color{R: 0.80, G: 0.42, B: 0.24})

	e.SetDayCycleSpeed(1.0 / 240.0)
	e.SetTimeOfDay(0.33)

	g.camera = glyph.NewCamera(9)
	g.camera.Target = mgl32.Vec3{0, 1.2, 0}
	g.camera.Pitch = 0.18

	log.Println("10-text running. Escape quits.")
	return nil
}

func (g *game) Update(e *glyph.Engine, dt float32) {
	in := e.Input()
	if in.KeyPressed(input.KeyEscape) {
		e.Close()
	}

	if t, ok := e.C.Transform.Get(g.cube); ok {
		t.Rotation[1] += 0.5 * dt
	}

	g.camera.Update(in)
	g.camera.ResolveCollision(e.Scene, 0, dt)
	e.SetCamera(g.camera.ViewVectors())

	w, h := e.Renderer().Extent()
	sw, sh := float32(w), float32(h)

	// One atlas at several sizes. A bitmap font would need a separate
	// rasterization per size and would still soften when scaled; the distance
	// field is resolution-independent, so these are all the same texture.
	lines := []renderer.TextLine{
		{Text: "GlyphEngine", X: 40, Y: 50, Scale: 64, Color: [3]float32{1, 1, 1}},
		{Text: "MSDF text, generated in pure Go", X: 40, Y: 128, Scale: 26,
			Color: [3]float32{0.75, 0.85, 1.0}},
		{Text: "no msdf-atlas-gen, no C++ toolchain", X: 40, Y: 160, Scale: 26,
			Color: [3]float32{0.75, 0.85, 1.0}},

		{Text: "The quick brown fox jumps over the lazy dog", X: 40, Y: sh - 130, Scale: 20,
			Color: [3]float32{0.95, 0.95, 0.95}},
		{Text: "0123456789 !@#$%^&*() {}[]<>/\\ .,;:'\"", X: 40, Y: sh - 100, Scale: 20,
			Color: [3]float32{0.95, 0.95, 0.95}},
		{Text: "small text stays legible at 13px (-range 8)", X: 40, Y: sh - 70, Scale: 13,
			Color: [3]float32{0.8, 0.8, 0.8}},

		// Negative X right-aligns against that margin.
		{Text: fmt.Sprintf("%.0f fps", e.FPS()), X: -40, Y: 50, Scale: 22,
			Color: [3]float32{0.6, 1.0, 0.6}},
	}
	g.text.SetText(e.Renderer(), lines, sw, sh)
	e.SetMSDFOverlays([]renderer.RenderObject{g.text.RenderObject(sw, sh, 48)})
}

func (g *game) Shutdown(e *glyph.Engine) {
	if g.text != nil {
		g.text.Destroy(e.Renderer())
	}
}

func main() {
	width := flag.Int("width", 1280, "window width")
	height := flag.Int("height", 720, "window height")
	fullscreen := flag.Bool("fullscreen", false, "run fullscreen on the primary monitor")
	frames := flag.Int("frames", 0, "render N frames then exit (0 = run until closed)")
	shot := flag.String("screenshot", "", "write a PNG of the last frame to this path")
	flag.Parse()

	opts := []glyph.Option{
		glyph.WithTitle("GlyphEngine - 10 Text"),
		glyph.WithWindowSize(*width, *height),
		glyph.WithMSAA(4),
	}
	if *fullscreen {
		opts = append(opts, glyph.WithFullscreen())
	}
	if *frames > 0 {
		opts = append(opts, glyph.WithMaxFrames(*frames))
	}
	if *shot != "" {
		opts = append(opts, glyph.WithScreenshot(*shot))
	}

	e, err := glyph.New(&game{}, opts...)
	if err != nil {
		log.Fatalf("create engine: %v", err)
	}
	defer e.Destroy()

	e.Run()
	log.Printf("rendered %d frames", e.FrameCount())
}
